"""Shared provenance and credit helpers for generated crawler artifacts."""
from __future__ import annotations

PROJECT = "Telegram Developer Crawler"
COPYRIGHT = "Copyright (C) 2026 Abhijeet Patil"

TL_HEADER = (
    "// This file is auto-generated by Telegram Developer Crawler.\n"
    "// " + COPYRIGHT + ".\n"
    "// Source: official Telegram developer data.\n"
)

MARKDOWN_COMMENT = (
    "<!-- This file is auto-generated by Telegram Developer Crawler. "
    + COPYRIGHT + ". -->\n"
)


def with_tl_credit(text: str) -> str:
    text = text.rstrip() + "\n"
    if text.startswith("// This file is auto-generated by Telegram Developer Crawler."):
        return text
    return TL_HEADER + "\n" + text


def with_markdown_credit(text: str) -> str:
    text = text.rstrip() + "\n"
    if text.startswith("<!-- This file is auto-generated by Telegram Developer Crawler."):
        return text
    return MARKDOWN_COMMENT + "\n" + text


def with_xml_credit(text: str) -> str:
    text = text.rstrip() + "\n"
    comment = "<!-- " + PROJECT + " generated snapshot. " + COPYRIGHT + ". -->"
    if comment in text:
        return text
    if text.startswith("<?xml") and "?>" in text:
        i = text.index("?>") + 2
        return text[:i] + "\n" + comment + text[i:]
    return comment + "\n" + text


def credit_diff(diff: str, comment: str | None = None) -> str:
    """Annotate every diff hunk with provenance without changing source files."""
    marker = comment or "// Telegram Developer Crawler — " + COPYRIGHT
    lines = diff.splitlines()
    out: list[str] = []
    for line in lines:
        if line.startswith("@@"):
            out.append(marker)
        out.append(line)
    return "\n".join(out) + ("\n" if diff.endswith("\n") else "")
