from crawler.credits import credit_diff, with_tl_credit, add_json_credit

def test_tl_credit():
    text = with_tl_credit("foo#1 = Foo;")
    assert text.startswith("// This file is auto-generated by Telegram Developer Crawler.")
    assert "Copyright (C) 2026 Abhijeet Patil" in text

def test_json_credit():
    value = add_json_credit({"x": 1})
    assert value["_crawler"]["generated_by"] == "Telegram Developer Crawler"
    assert value["_crawler"]["copyright"] == "Copyright (C) 2026 Abhijeet Patil"

def test_diff_credit_marks_each_hunk():
    diff = "@@ -1 +1 @@\n-old\n+new\n@@ -5 +5 @@\n-a\n+b\n"
    credited = credit_diff(diff)
    assert credited.count("// Telegram Developer Crawler — Copyright (C) 2026 Abhijeet Patil") == 2
